services/chocowrappers/chocowrappers/Models/User.cs
using System.Collections;
using System.Collections.Generic;

namespace chocowrappers.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public virtual ICollection<Chocolate> Chocolates { get; set; }
        public virtual ICollection<Wrapper> WrapperCollection { get; set; }

        public virtual ICollection<FriendRelation> FriendsFrom { get; set; }
        public virtual ICollection<FriendRelation> FriendsTo { get; set; }
    }

    public class FriendRelation
    {
        public int FromId { get; set; }
        public int ToId { get; set; }

        public virtual User UserFrom { get; set; }
        public virtual User UserTo { get; set; }
    }
}

services/chocowrappers/chocowrappers/Controllers/ChocolateController.cs
using System.Data;
using System.Linq;
using chocowrappers.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace chocowrappers.Controllers
{
    public class ChocolateController: BaseController
    {
        public ChocolateController(ChocoContext db) : base(db)
        {
        }
        public IActionResult ViewChocolate(int id)
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Login", "User");
            }
            var choco = Db.Chocolates
                .Include(c => c.User).ThenInclude(u => u.FriendsFrom)
                .FirstOrDefault(x => x.Id == id);
            if (choco == null)
            {
                return NotFound();
            }

            if (choco.UserId == GetCurrentUser().Id)
            {
                return View(choco);
            }

            var rel = choco.User.FriendsFrom.FirstOrDefault(r => r.FromId == GetCurrentUser().Id);
            if (rel != null)
            {
                return View(choco);
            }
            
            return NotFound();   
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Login", "User");
            }
            return View();
        }
        
        [HttpPost]
        public IActionResult CreatePost(Chocolate choco)
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Login", "User");
            }
            
            try
            {
                if (ModelState.IsValid)
                {
                    if (choco.UserId == 0)
                    {
                        choco.UserId = GetCurrentUser().Id;
                    }
                    Db.Chocolates.Add(choco);
                    Db.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View("Create", choco);
        }
    }
}

services/chocowrappers/chocowrappers/Controllers/UserController.cs
using System;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using chocowrappers.Helpers;
using chocowrappers.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace chocowrappers.Controllers
{
    public class UserController : BaseController
    {
        public UserController(ChocoContext db) : base(db)
        {
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegisterPost()
        {
            var username = Request.Form["username"].ToString();
            var password = Request.Form["password"].ToString();

            if (username == "" || password == "")
            {
                return BadRequest("need to provide username and password");
            }

            var user = Db.Users.FirstOrDefault(x => x.Name == username);
            if (user != null)
            {
                return BadRequest("user with this username already registered");
            }

            Db.Users.Add(new User {Name = username, Password = password});
            Db.SaveChanges();

            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LoginPost()
        {
            var username = Request.Form["username"].ToString();
            var password = Request.Form["password"].ToString();

            var user = Db.Users.FirstOrDefault(x => x.Name == username && x.Password == password);
            if (user == null)
            {
                return BadRequest("invalid credentials");
            }

            var authCookieString = user.Id + "." + user.Name;
            var signatureCookieString = AuthHelper.CalcSignature(authCookieString);

            var option = new CookieOptions();
            option.Expires = DateTime.Now.AddHours(24);
            HttpContext.Response.Cookies.Append("session", authCookieString, option);
            HttpContext.Response.Cookies.Append("sign", signatureCookieString, option);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {
            foreach (var cookie in Request.Cookies.Keys)
            {
                Response.Cookies.Delete(cookie);
            }

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Me()
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Login");
            }

            return View(GetCurrentUser());
        }

        public IActionResult ViewUser(int id)
        {
            if (GetCurrentUser() != null && id == GetCurrentUser().Id)
            {
                return RedirectToAction("Me");
            }

            var user = Db.Users
                .Include(x => x.Chocolates)
                .FirstOrDefault(x => x.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        public IActionResult List()
        {
            var users = Db.Users.ToList();
            return View(users);
        }

        [HttpGet]
        public IActionResult AddToFriendsRequest(int id)
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Login");
            }

            var friend = Db.Users.FirstOrDefault(x => x.Id == id);
            if (friend == null)
            {
                return NotFound();
            }

            return View(friend);
        }

        [HttpPost]
        public IActionResult AddToFriends(int id, string guesses)
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Login");
            }

            var wrapperNames = guesses.Split(",");
            if (wrapperNames.Length > 100)
            {
                return BadRequest("100 guesses maximum");
            }

            var friend = Db.Users.Include(u => u.WrapperCollection).FirstOrDefault(x => x.Id == id);
            if (friend == null)
            {
                return NotFound();
            }

            var rel = Db.FriendRelations.FirstOrDefault(r =>
                r.FromId == GetCurrentUser().Id && r.ToId == friend.Id);
            if (rel != null)
            {
                return BadRequest("Already friends!");
            }

            var cnt = 0;
            foreach (var item in friend.WrapperCollection)
            {
                if (wrapperNames.Contains(item.Name))
                {
                    cnt += 1;
                }
            }

            if (cnt * 2 <= friend.WrapperCollection.Count)
            {
                return BadRequest("You don't know this user, go away!");
            }

            var relation = new FriendRelation {FromId = GetCurrentUser().Id, ToId = id};
            Db.FriendRelations.Add(relation);
            Db.SaveChanges();

            return RedirectToAction("ViewUser", new {id});
        }
    }
}

services/chocowrappers/chocowrappers/Controllers/WrapperController.cs
using System.Data;
using System.Linq;
using chocowrappers.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace chocowrappers.Controllers
{
    public class WrapperController: BaseController
    {
        public WrapperController(ChocoContext db) : base(db)
        {
        }
        public IActionResult ViewWrapper(int id)
        {
            var wrapper = Db.Wrappers.Include(w => w.User).FirstOrDefault(x => x.Id == id);
            if (wrapper == null || wrapper.User != GetCurrentUser())
            {
                return NotFound();
            }
            return View(wrapper);
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Login", "User");
            }
            return View();
        }
        
        [HttpPost]
        public IActionResult CreatePost(Wrapper wrapper)
        {
            if (GetCurrentUser() == null)
            {
                return RedirectToAction("Login", "User");
            }
            
            try
            {
                if (ModelState.IsValid)
                {
                    if (wrapper.UserId == 0)
                    {
                        wrapper.UserId = GetCurrentUser().Id;
                    }
                    Db.Wrappers.Add(wrapper);
                    Db.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View("Create", wrapper);
        }
    }
}

services/chocowrappers/chocowrappers/Views/User/AddToFriendsRequest.cshtml
@model User

@{
    ViewData["Title"] = "Register page";
}

<div class="container justify-content-center">
    <div class="row justify-content-center">
        <div class="col justify-content-center">
            <form class="border border-light p-5" method="post" action="/User/AddToFriends">
                <div class="text-center">
                    <p class="h4 mb-4">Do you really know this user?</p>
                    <p class="h6 mb-1">Prove it by naming more than a half of his wrapper collection!</p>
                </div>
                <div class="form-group">
                    <input type="hidden" class="form-control" name="id" value="@Model.Id">
                </div>
                <div class="form-group">
                    <label for="guesses">Guesses</label>
                    <input type="text" class="form-control" id="guesses" name="guesses" aria-describedby="guessesHelp" placeholder="Enter your guesses">
                    <small id="guessesHelp" class="form-text text-muted">Comma-delimited names of wrappers, e.g. "kek,lol,mem"</small>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

services/chocowrappers/chocowrappers/Views/User/List.cshtml
@model IEnumerable<chocowrappers.Models.User>

@{
    ViewData["Title"] = "List of users";
}

<div class="container justify-content-center">
    <div class="row justify-content-center">
        <div class="col justify-content-center">
            @if (Model != null)
            {
                <table class="table">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Id)</th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.ActionLink("View", "ViewUser", "User", new {id = item.Id})
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>
    </div>
</div>

services/chocowrappers/chocowrappers/Views/User/Login.cshtml
@{
    ViewData["Title"] = "Register page";
}

<div class="container justify-content-center">
    <div class="row justify-content-center">
        <div class="col justify-content-center">
            <form class="border border-light p-5" method="post" action="/User/LoginPost">
                <div class="text-center">
                    <p class="h4 mb-4">Login</p>
                </div>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

services/chocowrappers/chocowrappers/Views/User/Me.cshtml
@model User

@{
    ViewData["Title"] = "Me";
}

<div class="container justify-content-center">
    <div class="row justify-content-center">
        <div class="col justify-content-center">
            <p class="h5">
                Hi,
                @Model.Name
                !
            </p>
            @if (Model.Chocolates != null)
            {
                <p>Here're your chocolates:</p>
                <table class="table">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Id)</th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.Chocolates)
                    {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @Html.ActionLink("View", "ViewChocolate", "Chocolate", new {id = item.Id})
                            </td>
                        </tr>
                    }
                </table>
            }
            <a href="/Chocolate/Create">
                <button class="btn-primary">Add a chocolate</button>
            </a>
        </div>
    </div>
    <div class="row mt-4 justify-content-center">
        <div class="col justify-content-center">
            @if (Model.FriendsTo != null)
            {
                <p>Here're your friends:</p>
                <table class="table">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Id)</th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.FriendsTo)
                    {
                        <tr>
                            <td>
                                @item.UserTo.Id
                            </td>
                            <td>
                                @item.UserTo.Name
                            </td>
                            <td>
                                @Html.ActionLink("View", "ViewUser", "User", new {id = item.ToId})
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>
    </div>
    <div class="row mt-4 justify-content-center">
        <div class="col justify-content-center">
            @if (Model.WrapperCollection != null)
            {
                <p>Here's your wrapper collection:</p>
                <table class="table">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Id)</th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.WrapperCollection)
                    {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @Html.ActionLink("View", "ViewWrapper", "Wrapper", new {id = item.Id})
                            </td>
                        </tr>
                    }
                </table>
            }
            <a href="/Wrapper/Create">
                <button class="btn-primary">Add a wrapper</button>
            </a>
        </div>
    </div>
</div>

services/chocowrappers/chocowrappers/Views/User/Register.cshtml
@{
    ViewData["Title"] = "Register page";
}

<div class="container justify-content-center">
    <div class="row justify-content-center">
        <div class="col justify-content-center">
            <form class="border border-light p-5" method="post" action="/User/RegisterPost">
                <div class="text-center">
                    <p class="h4 mb-4">Register</p>
                </div>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

services/chocowrappers/chocowrappers/Views/User/ViewUser.cshtml
@model User

@{
    ViewData["Title"] = "Me";
}

<div class="container justify-content-center">
    <div class="row justify-content-center">
        <div class="col justify-content-center">
            <p class="h5">
                This is @Model.Name's page.
            </p>
            @Html.ActionLink("Make friends", "AddToFriendsRequest", "User", new {id = Model.Id})
            @if (Model.Chocolates != null)
            {
                <p>Here're his chocolates:</p>
                <table class="table">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Id)</th>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.Chocolates)
                    {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @Html.ActionLink("View", "ViewChocolate", "Chocolate", new {id = item.Id})
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>
    </div>
</div>